wip: try to update to 4.0.0-dev commit efd54879ecbf8aac41fe809d31c7215ea3101241, but get the following error
    Updating crates.io index
error: failed to select a version for the requirement `frame-benchmarking = "^4.0.0-dev"`
candidate versions found which didn't match: 3.1.0, 3.0.0, 2.0.1, ...
location searched: crates.io index
required by package `datahighway v3.0.5 (/Users/ls2/code/DataHighway-DHX/node/node)`