WIP - travis ci fails to compile
error is the following

```
+cargo test -p node-runtime
    Updating git repository `https://github.com/paritytech/substrate.git`
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/parity-common`
error: failed to load source for a dependency on `kvdb`
Caused by:
  Unable to update https://github.com/paritytech/parity-common?rev=03a2ba08f47f4af4219280e660a1ea92cb8896bd#03a2ba08
Caused by:
  revspec '03a2ba08f47f4af4219280e660a1ea92cb8896bd' not found; class=Reference (4); code=NotFound (-3)
The command "./.ci/script.sh" exited with 101.
```