wip but error
error[E0277]: the trait bound `&BondedDHXForAccountData<<T as frame_system::Config>::AccountId, <<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance, <T as frame_system::Config>::AccountId>: EncodeLike<<<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance>` is not satisfied
   --> pallets/mining/rewards-allowance/src/lib.rs:282:96
    |
282 |                         <RewardsAllowanceDHXForDate<T>>::insert(requested_date_millis.clone(), &bonded_data);
    |                                                                                                ^^^^^^^^^^^^ the trait `EncodeLike<<<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance>` is not implemented for `&BondedDHXForAccountData<<T as frame_system::Config>::AccountId, <<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance, <T as frame_system::Config>::AccountId>`
    |
note: required by `frame_support::pallet_prelude::StorageMap::<Prefix, Hasher, Key, Value, QueryKind, OnEmpty, MaxValues>::insert`
   --> /Users/ls2/.cargo/git/checkouts/substrate-7e08433d4c370a21/852bab0/frame/support/src/storage/types/map.rs:142:2
    |
142 |     pub fn insert<KeyArg: EncodeLike<Key>, ValArg: EncodeLike<Value>>(key: KeyArg, val: ValArg) {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider introducing a `where` bound, but there might be an alternative better way to express this requirement
    |
244 |     impl<T: Config> Pallet<T> where &BondedDHXForAccountData<<T as frame_system::Config>::AccountId, <<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance, <T as frame_system::Config>::AccountId>: EncodeLike<<<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance> {
    |                               ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++